```{r}
library(papaja)
library(tidyverse)
library(fs)
library(xtable)
library(kableExtra)
library(cowplot)
library(scales)
library(estimatr)
library(broman)

source(path(here::here(), "file_paths.R"))
source(functions_script)
```

```{r}
options_table <- 
  read_csv(
    path(
      project_root,
      "paper",
      "options_table",
      ext = "csv"
    )
  ) %>% 
  filter(!is.na(`Study setting`)) %>% 
  mutate(
    Notes = case_when(
      is.na(`Notes`) ~ "--",
      TRUE ~ `Notes`
    )
  )


options_table %>%
  kbl(
    booktabs = TRUE,
    longtable = TRUE,
    linesep = "",
    caption = "Settings customizable by researchers when creating new studies to be run on the Web-CDI platform."
  ) %>%
  kable_styling(
    position = "center",
    latex_options = c("scale_down", "repeat_header")
  ) %>%
  column_spec(c(1, 3), width = "2.2in") %>%
  column_spec(2, width = "1.2in") %>%
  row_spec(0, bold = TRUE)

```

\newpage

```{r}
rownames <-
  c(
    "Intercept",
    "Age",
    "Caregiver education: Some college",
    "Caregiver education: High school or less",
    "Age * Caregiver education: Some college",
    "Age * Caregiver education: High school or less"
  )


comp_table <-
  ses_wg_lm_comp %>%
  tidy() %>%
  mutate(across(
    .cols = 2:7,
    .fns = ~ round(., digits = 3)
  )) %>% 
  mutate(term = rownames) %>%
  select(-outcome) %>%
  kbl(
    booktabs = TRUE,
    linesep = "",
    caption = "Regression output for WG comprehension measure."
  ) %>%
  kable_styling(
    position = "center",
    latex_options = "scale_down"
  )

comp_table

prod_table <-
  ses_wg_lm_prod %>%
  tidy() %>%
  mutate(across(
    .cols = 2:7,
    .fns = ~ round(., digits = 3)
  )) %>% 
  mutate(term = rownames) %>%
  select(-outcome) %>%
  kbl(
    booktabs = TRUE,
    linesep = "",
    caption = "Regression output for WG production measure."
  ) %>%
  kable_styling(
    position = "center",
    latex_options = "scale_down"
  )

prod_table
```

\newpage

```{r}

load(ws_cutoffs_path)
load(wg_cutoffs_path)

facebook_wg_cutoffs %>%
  arrange(age) %>% 
  mutate(minimum_time = round(minimum_time, digits = 3)) %>% 
  mutate(
    age = as.character(age), 
    minimum_time = as.character(minimum_time)
  ) %>% 
  rename(
    "Age in months" = age,
    "Minimum time to\ncompletion (minutes)" = minimum_time
  ) %>% 
  kbl(
    align = "l", 
    linesep = "", 
    caption = "Minimum times to completion, WG measure", 
    booktabs = TRUE
  ) %>% 
  kable_styling(
    position = "center",
  ) %>% 
  column_spec(column = 2, width = "2.2in")

prolific_ws_cutoffs %>%
  arrange(age) %>% 
  mutate(minimum_time = round(minimum_time, digits = 3)) %>% 
  mutate(
    age = as.character(age), 
    minimum_time = as.character(minimum_time)
  ) %>% 
  rename(
    "Age in months" = age,
    "Minimum time to\ncompletion (minutes)" = minimum_time
  ) %>% 
  kbl(
    align = "l", 
    linesep = "", 
    caption = "Minimum times to completion, WG measure", 
    booktabs = TRUE
  ) %>% 
  kable_styling(
    position = "center",
  ) %>% 
  column_spec(column = 2, width = "2.2in")

```

